name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore WAD.sln


    - name: Build
      run: dotnet build WAD.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test WAD.sln --no-build --configuration Release --verbosity normal
